In [1]:
# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np

# Visualización
# ------------------------------------------------------------------------------
import matplotlib.pyplot as plt
import seaborn as sns

# Evaluar linealidad de las relaciones entre las variables
# y la distribución de las variables
# ------------------------------------------------------------------------------
#import scipy.stats as stats
import scipy.stats as stats
from scipy.stats import shapiro, kstest

# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames 


# Gestión de los warnings
# -----------------------------------------------------------------------
import warnings
warnings.filterwarnings("ignore")

## Dataset: `menstrual_cycle_data.csv`

[Source](https://www.kaggle.com/datasets/nikitabisht/menstrual-cycle-data/data)

In [2]:
df_cycle_general = pd.read_csv('files/raw/menstrual_cycle_data.csv')

df_cycle_general.head()

ClientID  CycleNumber  Group  CycleWithPeakorNot  ReproductiveCategory  \
0  nfp8122            1      0                   1                     0   
1  nfp8122            2      0                   1                     0   
2  nfp8122            3      0                   1                     0   
3  nfp8122            4      0                   1                     0   
4  nfp8122            5      0                   1                     0   

   LengthofCycle MeanCycleLength EstimatedDayofOvulation LengthofLutealPhase  \
0             29           27.33                      17                  12   
1             27                                      15                  12   
2             29                                      15                  14   
3             27                                      15                  12   
4             28                                      16                  12   

  FirstDayofHigh TotalNumberofHighDays TotalHighPostPeak  \
0             12                     5                 0   
1             13                     2                 0   
2                                    1                 0   
3             13                     2                 0   
4             12                     4                 0   

  TotalNumberofPeakDays TotalDaysofFertility TotalFertilityFormula  \
0                     2                    9                    15   
1                     2                    6                    13   
2                     2                    5                    13   
3                     2                    6                    13   
4                     2                    8                    14   

  LengthofMenses MeanMensesLength MensesScoreDayOne MensesScoreDayTwo  \
0              5             4.49                 3                 3   
1              5                                  3                 3   
2              5                                  3                 3   
3              5                                  3                 3   
4              5                                  3                 3   

  MensesScoreDayThree MensesScoreDayFour MensesScoreDayFive MensesScoreDaySix  \
0                   2                  1                  1                     
1                   2                  1                  1                     
2                   2                  1                  1                     
3                   3                  2                  1                     
4                   2                  2                  1                     

  MensesScoreDaySeven MensesScoreDayEight MensesScoreDayNine  \
0                                                              
1                                                              
2                                                              
3                                                              
4                                                              

  MensesScoreDayTen MensesScoreDay11 MensesScoreDay12 MensesScoreDay13  \
0                                                                        
1                                                                        
2                                                                        
3                                                                        
4                                                                        

  MensesScoreDay14 MensesScoreDay15 TotalMensesScore MeanBleedingIntensity  \
0                                                 10                  9.04   
1                                                 10                         
2                                                 10                         
3                                                 12                         
4                                                 11                         

  NumberofDaysofIntercourse IntercourseInFertileWindow Un

In [4]:
df_cycle_general.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1665 entries, 0 to 1664
Data columns (total 80 columns):
 #   Column                      Non-Null Count  Dtype 
---  ------                      --------------  ----- 
 0   ClientID                    1665 non-null   object
 1   CycleNumber                 1665 non-null   int64 
 2   Group                       1665 non-null   int64 
 3   CycleWithPeakorNot          1665 non-null   int64 
 4   ReproductiveCategory        1665 non-null   int64 
 5   LengthofCycle               1665 non-null   int64 
 6   MeanCycleLength             1665 non-null   object
 7   EstimatedDayofOvulation     1665 non-null   object
 8   LengthofLutealPhase         1665 non-null   object
 9   FirstDayofHigh              1665 non-null   object
 10  TotalNumberofHighDays       1665 non-null   object
 11  TotalHighPostPeak           1665 non-null   object
 12  TotalNumberofPeakDays       1665 non-null   object
 13  TotalDaysofFertility        1665 non-null   obje

In [31]:
df_cycle_general.columns


Index(['ClientID', 'CycleNumber', 'Group', 'CycleWithPeakorNot',
       'ReproductiveCategory', 'LengthofCycle', 'MeanCycleLength',
       'EstimatedDayofOvulation', 'LengthofLutealPhase', 'FirstDayofHigh',
       'TotalNumberofHighDays', 'TotalHighPostPeak', 'TotalNumberofPeakDays',
       'TotalDaysofFertility', 'TotalFertilityFormula', 'LengthofMenses',
       'MeanMensesLength', 'MensesScoreDayOne', 'MensesScoreDayTwo',
       'MensesScoreDayThree', 'MensesScoreDayFour', 'MensesScoreDayFive',
       'MensesScoreDaySix', 'MensesScoreDaySeven', 'MensesScoreDayEight',
       'MensesScoreDayNine', 'MensesScoreDayTen', 'MensesScoreDay11',
       'MensesScoreDay12', 'MensesScoreDay13', 'MensesScoreDay14',
       'MensesScoreDay15', 'TotalMensesScore', 'MeanBleedingIntensity',
       'NumberofDaysofIntercourse', 'IntercourseInFertileWindow',
       'UnusualBleeding', 'PhasesBleeding', 'IntercourseDuringUnusBleed',
       'Age', 'AgeM', 'Maristatus', 'MaristatusM', 'Yearsmarried', 'Wedding

In [11]:
df_cycle_general['ClientID'].unique()

array(['nfp8122', 'nfp8114', 'nfp8109', 'nfp8107', 'nfp8106', 'nfp8024',
       'nfp8020', 'nfp8026', 'nfp8030', 'nfp8031', 'nfp8032', 'nfp8034',
       'nfp8036', 'nfp8040', 'nfp8041', 'nfp8042', 'nfp8043', 'nfp8045',
       'nfp8046', 'nfp8047', 'nfp8049', 'nfp8050', 'nfp8051', 'nfp8057',
       'nfp8058', 'nfp8060', 'nfp8062', 'nfp8063', 'nfp8064', 'nfp8066',
       'nfp8068', 'nfp8069', 'nfp8072', 'nfp8073', 'nfp8074', 'nfp8076',
       'nfp8079', 'nfp8080', 'nfp8083', 'nfp8085', 'nfp8087', 'nfp8091',
       'nfp8094', 'nfp8099', 'nfp8100', 'nfp8101', 'nfp8102', 'nfp8110',
       'nfp8113', 'nfp8116', 'nfp8123', 'nfp8124', 'nfp8129', 'nfp8131',
       'nfp8133', 'nfp8137', 'nfp8140', 'nfp8143', 'nfp8144', 'nfp8149',
       'nfp8150', 'nfp8152', 'nfp8154', 'nfp8155', 'nfp8159', 'nfp8161',
       'nfp8164', 'nfp8165', 'nfp8168', 'nfp8172', 'nfp8173', 'nfp8174',
       'nfp8176', 'nfp8177', 'nfp8178', 'nfp8179', 'nfp8184', 'nfp8186',
       'nfp8187', 'nfp8188', 'nfp8189', 'nfp8190', 

In [17]:
df_filtered = df_cycle_general.groupby('ClientID')['CycleNumber'].apply(list)

In [22]:
df_filtered[-1]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [32]:
df_cycle_general['Group'].unique()

array([0, 1], dtype=int64)

In [34]:
df_cycle_general['CycleWithPeakorNot'].unique()

array([1, 0], dtype=int64)

In [36]:
df_cycle_general['ReproductiveCategory'].unique()

array([0, 2, 1, 9], dtype=int64)

In [44]:
df_cycle_general['ClientID'][df_cycle_general['MeanCycleLength'] == ' '].count()

1524

In [46]:
df_cycle_general['FirstDayofHigh'].unique()

array(['12', '13', ' ', '10', '9', '8', '14', '11', '16', '6', '15', '17',
       '21', '7', '19', '18', '5', '22', '20', '24', '23', '26', '25'],
      dtype=object)

In [47]:
df_cycle_general['ClientID'][df_cycle_general['FirstDayofHigh'] == ' '].count()

258

In [49]:
df_cycle_general['ClientID'].nunique()

159

In [51]:
df_cycle_general['MensesScoreDayTwo'].unique()

array(['3', '2', '1', ' '], dtype=object)

The dataset is too long and it contains useless columns for our objectives. We decide to select the columns that might be of use. 

In [54]:
df_cycle_general = df_cycle_general[['ClientID', 'CycleNumber', 'LengthofCycle', 'MeanCycleLength', 'EstimatedDayofOvulation', 'LengthofLutealPhase', 'LengthofMenses',
       'MeanMensesLength', 'MensesScoreDayOne', 'MensesScoreDayTwo', 'MensesScoreDayThree', 'MensesScoreDayFour', 'MensesScoreDayFive',
       'MensesScoreDaySix', 'MensesScoreDaySeven', 'MensesScoreDayEight', 'MensesScoreDayNine', 'MensesScoreDayTen', 'MensesScoreDay11',
       'MensesScoreDay12', 'MensesScoreDay13', 'MensesScoreDay14', 'MensesScoreDay15', 'TotalMensesScore', 'MeanBleedingIntensity', 
       'UnusualBleeding', 'PhasesBleeding', 'Age', 'Ethnicity', 'BMI']]

In [58]:
df_cycle_general['ClientID'][df_cycle_general['MeanMensesLength'] == ' '].count()

1524

In [62]:
menses_columns  = [col for col in df_cycle_general if "Menses" in col]

menses_columns 

['LengthofMenses',
 'MeanMensesLength',
 'MensesScoreDayOne',
 'MensesScoreDayTwo',
 'MensesScoreDayThree',
 'MensesScoreDayFour',
 'MensesScoreDayFive',
 'MensesScoreDaySix',
 'MensesScoreDaySeven',
 'MensesScoreDayEight',
 'MensesScoreDayNine',
 'MensesScoreDayTen',
 'MensesScoreDay11',
 'MensesScoreDay12',
 'MensesScoreDay13',
 'MensesScoreDay14',
 'MensesScoreDay15',
 'TotalMensesScore']

In [67]:
for col in menses_columns:
    print(col, '-->', df_cycle_general['ClientID'][df_cycle_general[col] == ' '].count())
    print(df_cycle_general[col].unique())
    print('=' * 50)

LengthofMenses --> 4
['5' '4' '6' '7' '10' '3' '8' '2' '9' '11' ' ' '15']
MeanMensesLength --> 1524
['4.49' ' ' '4.5' '6.67' '4.75' '4.33' '4.67' '5.31' '6' '5.63' '5.33'
 '5.5' '5.2' '4.63' '5.45' '6.42' '6.5' '3.92' '5' '5.14' '6.23' '5.54'
 '7' '3.9' '4.69' '4.25' '7.14' '4.38' '4' '3.67' '3.23' '4.46' '5.69'
 '4.54' '2.85' '6.75' '8.58' '5.62' '5.67' '4.77' '6.38' '4.45' '5.8'
 '5.21' '6.45' '3.83' '4.83' '5.25' '4.22' '6.07' '2.4' '6.21' '5.08'
 '5.12' '6.25' '5.92' '3.94' '4.17' '6.88' '5.75' '3.5' '6.86' '5.17'
 '5.89' '5.84' '5.6' '7.46' '8.25' '5.16' '6.53' '4.7' '4.92' '7.08'
 '5.73' '5.64' '4.47' '4.85']
MensesScoreDayOne --> 4
['3' '1' '2' ' ']
MensesScoreDayTwo --> 4
['3' '2' '1' ' ']
MensesScoreDayThree --> 25
['2' '3' '1' ' ']
MensesScoreDayFour --> 87
['1' '2' '3' ' ']
MensesScoreDayFive --> 434
['1' ' ' '2' '3']
MensesScoreDaySix --> 1062
[' ' '1' '2' '3']
MensesScoreDaySeven --> 1441
[' ' '1' '2' '3']
MensesScoreDayEight --> 1597
[' ' '1' '2']
MensesScoreDayNine --> 1